### ISSUE TITLE
Make CI-step `build_no_std` mandatory for PRs

### ISSUE THREAD

**Issue by phip1611** [rust-osdev/multiboot2#105]
This arises from #101.

TL;DR: require no_std-builds to pass in CI for newPRs

@IsaacWoods  I do not have admin rights to change this.

**Comment by IsaacWoods** [comment]
@phip1611 I've added a branch protection rule for `main` that should enforce this.

I'm also aware that I've had a lot less time to commit to maintenance than before, so I've made you a maintainer of the team and given you admin privileges for this repo. Thank you for your work on the project!
