### ISSUE TITLE
Evaluate Interface for Custom Tags

### ISSUE THREAD

**Issue by phip1611** [rust-osdev/multiboot2#116]
I've seen people using custom Multiboot2 tags to transfer data from a custom bootloader to their kernel. We should evaluate if and how we want or can support this.

**Comment by blitz** [comment]
To formulate this as a usecase: As a user of this library I would like to be able to support custom tags. The library should not limit the user to the tags in the current spec and allow the user to define completely custom tags.

**Comment by IsaacWoods** [comment]
I think this could be achieved fairly easily by exposing `BootInformation::get_tag` (which imo should be renamed `tag` but that's a nit) and reworking `TagType` to support custom values (e.g. remove the `repr(u32)`, add a `Custom(u32)` variant, and adding manual `From<u32>` and `Into<u32>` impls)?

**Comment by phip1611** [comment]
Closed with #118
