### ISSUE TITLE
multiboot2-header: various improvements

### ISSUE THREAD

**Issue by phip1611** [rust-osdev/multiboot2#135]
- rename std module to alloc
- multiboot2_header::load should return not only a byte slice (seen in <https://github.com/rust-osdev/multiboot2/pull/136>)
- also, the assertion could be transformed into a variant of the error enum

**Comment by YtvwlD** [comment]
Yeah, I'm not sure about the byte slice. This can be useful to be able to discard the rest of the file.

**Comment by phip1611** [comment]
It's okay, I can also work on this eventually. This is technical debt that wasn't introduced by you
