### ISSUE TITLE
Multiboot 1 support

### ISSUE THREAD

**Issue by cornytrace** [rust-osdev/multiboot2#139]
Multiboot2 is a fine spec in theory, but in practice there are only a few bootloaders which support it. More importantly, qemu has support for directly loading Multiboot 1 kernels, but not mb2. Ideally I want the ability to parse mb1 structures and build them via the builder. Maybe even build hybrid mb1/mb2 binaries for maximum compatibility with bootloaders. I'm willing to do the work myself, but for that I have the following questions:
Do you want multiboot1 support in this crate or should it be a separate crate?
If yes, should it be behind a feature flag? Default on or off?
Should I put the mb1 files in the src directory prefixed with mb1_ or in a seperate mb1 folder/module?

**Comment by phip1611** [comment]
Hi @cornytrace 
I appreciate your initiative and motivation! 

> Multiboot2 is a fine spec in theory, but in practice there are only a few bootloaders which support it.

For publicly available bootloaders, I agree. However, I think that there are a lot of closed-source company-internal multiboot2 bootloaders out there. At least I know two companies that use custom internal multiboot2 bootloaders.

> Maybe even build hybrid mb1/mb2 binaries for maximum compatibility with bootloaders.

Yes, that's a valid point. But at least for this, one doesn't need this crate at all.

See https://github.com/cyberus-technology/hedron/blob/80a1e2710902e53cc98704e46dbbc59c304abab6/src/start.S#L84-L110 for example.


> Do you want multiboot1 support in this crate or should it be a separate crate?

I don't think that having multiboot1 functionality in a "multiboot2" crate makes sense for the following reasons:
- increased repo complexity (project setups and CI all needs to be kept in sync for every sub project)
- people do not expect multiboot1 functionality in a crate called multiboot2
- there is a multiboot1 crate <https://crates.io/crates/multiboot> - have you checked this one out?

In case there are valid reasons to create a new multiboot v1 crate and you develop it to a stage where it is mature, feature-complete and has a clear value-add compared to the existing crate, I think we can also move it under the umbrella of the rust-osdev organization on GitHub - if you like.

**Comment by cornytrace** [comment]
>     * there is a multiboot1 crate https://crates.io/crates/multiboot - have you checked this one out?
D'oh! I can't believe I missed that crate.
Thanks for all your pointers and explanations.
