### ISSUE TITLE
How to get elf information?

### ISSUE THREAD

**Issue by mldulaney** [rust-osdev/multiboot2#244]
Used to be, i could simply iterate through elf_sections_tag.sections() and get what I wanted, but that is no longer the case.  What is the current way to get things like e.g. the elf section size and location for each section?

**Comment by mldulaney** [comment]
I guess i should point out my ultimate goal is to get os size (and possibly in the future location)

**Comment by phip1611** [comment]
Hi!

What about https://docs.rs/multiboot2/0.23.0/multiboot2/struct.BootInformation.html#method.elf_sections, isn't this what you need?

**Comment by mldulaney** [comment]
Yeah, I can't see any public methods to actually get the data i want out.

**Comment by phip1611** [comment]
> Yeah, I can't see any public methods to actually get the data i want out.

Which data do you want to get?

**Comment by mldulaney** [comment]
i'll check it out this evening.  my ultimate goal is to find the location and size of my kernel in memory, and i was hoping to use the elf tags to do so.

**Comment by mldulaney** [comment]
groovy, this seems to have done the trick, thanks!

**Comment by phip1611** [comment]
Fixed with [v0.23.1](https://crates.io/crates/multiboot2/0.23.1).
