### ISSUE TITLE
Maintainance of this crate

### ISSUE THREAD

**Issue by phil-opp** [rust-osdev/multiboot2#32]
Hi! I haven't had the time to maintain this crate. There are a few outstanding issues and pull requests in this repository and various forks have spawned. So I thought about how we could improve the situation.

The most important question is: **Is anybody willing to maintain this crate?**

If not, I would propose to give all interested people push access, but require pull requests and reviews for all changes. There is also a travis check in place that ensures that the crate always builds and that the tests always pass. This way, the crate could be developed further without a dedicated maintainer.

We could also move this crate to a Github organization if there's interest, and give more people push access to crates.io.

What do you think?

cc:

@ahmedcharles 
@robert-w-gries
@aeleos
@Columbus240
@le-jzr 
@4e554c4c

**Comment by robert-w-gries** [comment]
I am interested in push access and can help review/merge

**Comment by phil-opp** [comment]
Awesome! You should have push access now.

**Comment by ahmedcharles** [comment]
This seems like a reasonable plan.

**Comment by 4e554c4c** [comment]
I don't have the time to maintain the crate right now. However I'll put some more time into reviewing and pushing changes.

**Comment by le-jzr** [comment]
Hey guys. I'd love to help, but I'm currently swamped with non-Rust work. I'll try to review changes from time to time, but no promises. :)

**Comment by phil-opp** [comment]
Thanks a lot, to both of you!

**Comment by phil-opp** [comment]
Just as a heads up: I transferred this repository to our newly created “rust-osdev” organization. @lachlansneff and I created it to bundle all kinds of tools and libraries related to Rust OS development. Let me know if you'd like to be members too! You all still have push access, of course :).

**Comment by ahmedcharles** [comment]
Thanks, this seems like a good idea.

**Comment by robert-w-gries** [comment]
I'd like to be a member! I think consolidating the rust-os tools is a great idea.

**Comment by phil-opp** [comment]
@robert-w-gries Cool, invitation sent!

**Comment by le-jzr** [comment]
Awesome! I'd like to be a member too. :)

**Comment by phil-opp** [comment]
@le-jzr Great! I invited you :).

**Comment by jzck** [comment]
hi all, I've been fiddling with this crate for a bit now, it seems that there's been a good deal of change since `0.3.2`, and many things fixed in master, is there a plan to make a new release and publish to crates.io ?

**Comment by phil-opp** [comment]
@jzck Thanks for bringing this up! I published the current state as `0.5.0`. The docs should update shortly.

(I used my release tool in a wrong way so that we accidentally skipped version `0.4`, but it shouldn't matter.)

**Comment by xacrimon** [comment]
I would be interested in helping to maintain this crate be a part of rust-osdev

**Comment by phil-opp** [comment]
@xacrimon Cool! I sent you an invitation to the rust-osdev organization and gave you write access to this repo. Note that any change to this repo requries a pull request with at least one accepting review before it can be merged. Thanks for your help!

**Comment by xacrimon** [comment]
@phil-opp Thanks! I usually enforce the same pull policy on all my repos too. Note that I have my finals coming up so I'll strapped for time for a week or two.

**Comment by phil-opp** [comment]
Just as a heads up: I created the @rust-osdev/multiboot2-elf64 team for the maintainance of this crate instead of giving individual people write access (the outside collaborators still have individual write access). This gives us a nice team discussion page and allows pinging the whole team if required.

**Comment by xacrimon** [comment]
:thumbsup

**Comment by mental32** [comment]
I'm a little late to the party buuuut I'm also interested in helping out to maintain this crate! :smile:

**Comment by phil-opp** [comment]
@mental32 Awesome! I sent you an invite to the rust-osdev organization.

**Comment by phip1611** [comment]
I close this for now because currently there are no maintenance problems, ok?
