### ISSUE TITLE
multiboot2-header is not `no_std`

### ISSUE THREAD

**Issue by chbaker0** [rust-osdev/multiboot2#98]
The docs claim the library is `no_std` in the second sentence of the front page: https://github.com/rust-osdev/multiboot2/blob/main/multiboot2-header/README.md?plain=1#L7

However the code references `std` in multiple places:

`Multiboot2HeaderBuilder::build()`: https://github.com/rust-osdev/multiboot2/blob/main/multiboot2-header/src/header/builder.rs#L129

`std` is `use`d in the beginning of lib.rs: https://github.com/rust-osdev/multiboot2/blob/main/multiboot2-header/src/lib.rs#L74

When I got build errors using this I was hoping there would be a `std` feature I could turn off, but it doesn't exist :(

The docs should probably be updated

**Comment by phip1611** [comment]
Ohhh... Thank you for the hint! I'll fix it asap so that it is no_std and include a test in CI

**Comment by phip1611** [comment]
@chbaker0 fixed in v0.1.1! public on crates.io

**Comment by chbaker0** [comment]
Awesome! Thanks for the quick response!
